### ISSUE TITLE
Exception when updating a product when optional fields are null

### ISSUE THREAD

**Issue by medteck** [BitBagCommerce/SyliusVueStorefrontPlugin#101]
When I attempt to edit a product via the Sylius backoffice, I get an exception if:

* Description or Short Description is null:
This is the error I get : 
`{"result":"Argument 17 passed to BitBag\\SyliusVueStorefrontPlugin\\Document\\Product\\Details::__construct() must be of the type string, null given, called in \/home\/medteck\/Documents\/Projects\/Jaba\/jaba-sylius\/vendor\/bitbag\/vuestorefront-plugin\/src\/Sylius\/Transformer\/SyliusProduct\/ProductDetailsTransformer.php on line 50","code":500}`

* Or Product has no media file uploaded:
This is the error I get:
`{"result":"Call to a member function getPath() on bool","code":500}`

* And sometimes, when the attribute "type" for media is null

**Comment by Codeweld** [comment]
Fixed by #102. Thank you @medteck for your input
