### ISSUE TITLE
SymfonyCloud installing assets error

### ISSUE THREAD

**Issue by johnnypea** [BitBagCommerce/SyliusVueStorefrontPlugin#119]
What is the recommended setup here? I followed https://docs.sylius.com/en/latest/cookbook/deployment/symfonycloud.html. Thanks.

```
❯ symfony ssh bin/console sylius:install:assets
WARNING Connecting to the master environment of the app application
Installing Sylius assets for environment prod.

Cannot run command due to bad directory permissions (tried to change permissions to 0755).

Set "/app/public" writable and run command "sylius:install:assets"
                                
  Process exited with status 1
```

**Comment by Cholin2000** [comment]
The current solution is deprecated as it was created for Vue Storefront v1. For Vue Storefront 2 integration check out our GraphQL-based integration - https://github.com/BitBagCommerce/SyliusVueStorefront2Plugin
