### ISSUE TITLE
Root mapping definition has unsupported parameters

### ISSUE THREAD

**Issue by azamalvi** [BitBagCommerce/SyliusVueStorefrontPlugin#121]
I have performed all the steps and in last  when I try to run `php bin/console fos:elastica:populate` then it throws below error.

```
 Root mapping definition has unsupported parameters:  [attribute : {dynamic_date_formats=[], _meta={mode  
  l=App\Entity\Product\ProductOption}, properties={attribute_id={type=long}, options={type=nested, proper  
  ties={value={type=text}}}, id={type=long}, enabled={type=text}}}] [reason: Failed to parse mapping [_do  
  c]: Root mapping definition has unsupported parameters:  [attribute : {dynamic_date_formats=[], _meta={  
  model=App\Entity\Product\ProductOption}, properties={attribute_id={type=long}, options={type=nested, pr  
  operties={value={type=text}}}, id={type=long}, enabled={type=text}}}]] 
```

Also I have a question that now when I open the site it is showing the default Sylius shop view and I was expecting that it's shop view should be some predefined VS theme. I'm unclear about it kindly tell me should I need to make a theme separately or we can use VS default theme.
Thanks.

**Comment by Codeweld** [comment]
Which Elasticsearch version do you use? You can check it at `http://localhost:9200/`.
Our plugin needs 6.8.X for now since there is no stable release of FOSElastica 6.0.0 which will support ES7.
