### ISSUE TITLE
Plugin requires symfony/serializer compatible with v5.0, but sylius/sylius requires it compatible with v4.4

### ISSUE THREAD

**Issue by andrei1152** [BitBagCommerce/SyliusVueStorefrontPlugin#122]
bitbag/vuestorefront-plugin v2.1.0 requires symfony/serializer ^5.0 -> found symfony/serializer[v5.0.0, ..., v5.2.1] but the package is fixed to v4.4.18 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

I've noticed that the "sylius/sylius" package has a dependency requirement for  "symfony/serializer": "^4.4", which I suppose is the cause of the problem.

**Comment by 3kynox** [comment]
Did you fixed it?
