### ISSUE TITLE
SyliusVueStorefrontPlugin + VueStoreFront

### ISSUE THREAD

**Issue by silcki** [BitBagCommerce/SyliusVueStorefrontPlugin#126]
Hello guys
I installed your plugin, installed VueStoreFront, ran it all, and got an issue:
when VueStoreFront does a request to `http://localhost/vsbridge/catalog/vue_storefront_catalog/attribute/_search` it can't load the response
When I call it in the browser's tab I get something like that
```
<result>
    <entry>2</entry>
    <entry>false</entry>
    <entry>
        <entry>5</entry>
        <entry>5</entry>
        <entry>0</entry>
        <entry>0</entry>
    </entry>
</result>
```
after debugging I found out that the FosResBundle uses JMS serializer as the default. I remembered that in your composer.json you set Symfony serializer 5 as required
I tuned the FosResBundle
```
fos_rest:
    service:
        serializer: fos_rest.serializer.symfony
```
and after that, I got as  the response
```
<response>
    <took>2</took>
    <timed_out>0</timed_out>
    <_shards>
        <total>5</total>
        <successful>5</successful>
        <skipped>0</skipped>
        <failed>0</failed>
    </_shards>
    <hits>
        <total>12</total>
        <max_score>1</max_score>
        <hits>
            ...
        </hits>
    </hits>
</response>
```
but unfortunately, it didn't help me
What do I do wrong?
| Soft | Version |
|-------|------------|
| Symfony | v4.4.18 | 
| Sylius | v1.8.8 | 
| SyliusVueStorefrontPlugin | v2.1.1 |
| VueStoreFront | v1.12.2 |

**Comment by silcki** [comment]
Hello guys
I figured out where was my problem
When I was installing the VueStoreFront I chose the theme Capybara, with the default theme everything works fine

**Comment by andrei1152** [comment]
@silcki I've got a different problem but maybe it can solve mine too

**Comment by Codeweld** [comment]
As @silcki said, only the default theme can be used. We don't support the Capybara theme for now.

**Comment by nickvanderzwet** [comment]
```
fos_rest:
    service:
        serializer: fos_rest.serializer.symfony
```

Shouldn't this be part of the README?
