### ISSUE TITLE
API Docs generation

### ISSUE THREAD

**Issue by silcki** [BitBagCommerce/SyliusVueStorefrontPlugin#127]
Hello guys
When I try to generate the API Doc via Api Platform Swagger I get an error
`{"result":"Resource \u0022App\\Entity\\Order\\OrderItem\u0022 not found.","code":500}`
After not long debugging I figured out that you override `sylius.model.order_item.class` to your model and I had to override it again back to `App\Entity\Order\OrderItem`
I understand why I should extend my model, but I can't understand why you override the parameter for API declaration?

**Comment by Cholin2000** [comment]
The current solution is deprecated as it was created for Vue Storefront v1. For Vue Storefront 2 integration check out our GraphQL-based integration - https://github.com/BitBagCommerce/SyliusVueStorefront2Plugin
