### ISSUE TITLE
The mistake in the readme file

### ISSUE THREAD

**Issue by silcki** [BitBagCommerce/SyliusVueStorefrontPlugin#129]
Hello everyone
Seems in the readme file you made a mistake
now is

> Set content of your config/fos_elastica.yaml to the following:

but should be

> Set content of your config/packages/fos_elastica.yaml to the following:

yes, with your current description everything works, but this is  thanks to this line

> - { resource: "@SyliusVueStorefrontPlugin/Resources/config/config.yaml" }

if I create the FOS config here `config/fos_elastica.yaml` the framework won't see it and won't parse it 
and if you try to add the new index it won't be working

**Comment by Cool-and-Deadly** [comment]
Yes I also think the readme should be updated

**Comment by Cholin2000** [comment]
The current solution is deprecated as it was created for Vue Storefront v1. For Vue Storefront 2 integration check out our GraphQL-based integration - https://github.com/BitBagCommerce/SyliusVueStorefront2Plugin
