### ISSUE TITLE
Environment variable not found "ELASTICSEARCH_URL" - Installation error

### ISSUE THREAD

**Issue by robin-aeist** [BitBagCommerce/SyliusVueStorefrontPlugin#133]
Hello,

I am working on a project with docker, Sylius 1.8 and Vue FrontStore.
My docker Sylius works well, the docker Vue Storefront too. So I have 12 containers :
vue-storefront_app_1
vue-storefront-api_redis_1
vue-storefront-api_kibana_1
vue-storefront-api_app_1
Sylius_git
Sylius_mysql
Sylius_mailhog
Sylius_pma
Sylius_php
Sylius_nginx => Doesn't work with vue-storefront-api (It wants to be on the same port)
Sylius_gulp

After correct the commandbus error for "composer require bitbag/vuestorefront-plugin:v2.1.1"
I have a new error:
> In EnvVarProcessor.php line 171:
> Environment variable not found: "ELASTICSEARCH_URL".

Do you have any idea ?

**Comment by Cholin2000** [comment]
The current solution is deprecated as it was created for Vue Storefront v1. For Vue Storefront 2 integration check out our GraphQL-based integration - https://github.com/BitBagCommerce/SyliusVueStorefront2Plugin
