### ISSUE TITLE
Log in into admin throws error

### ISSUE THREAD

**Issue by sangamu** [BitBagCommerce/SyliusVueStorefrontPlugin#134]
I integrated this plugin into sylius standard 1.8.6. After integration, public shop (which I have not disabled yet) works fine. But I get error while trying to log into admin. Here is the error:

> {"result":"An exception has been thrown during the rendering of a template (\u0022An exception occurred while executing \u0027SELECT t0.quantity AS quantity_1, t0.unit_price AS unit_price_2, t0.units_total AS units_total_3, t0.adjustments_total AS adjustments_total_4, t0.total AS total_5, t0.is_immutable AS is_immutable_6, t0.id AS id_7, t0.product_name AS product_name_8, t0.variant_name AS variant_name_9, t0.uuid AS uuid_10, t0.order_id AS order_id_11, t0.variant_id AS variant_id_12 FROM sylius_order_item t0 WHERE t0.order_id = ?\u0027 with params [12]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column \u0027t0.uuid\u0027 in \u0027field list\u0027\u0022).","code":500}

Trying to fix, I added "doctrine/inflector": "^1.4" in conflict section of composer (while having "bitbag/vuestorefront-plugin": "v2.1.1" in require section) and ran "composer update". But the problem does not go away. Did I miss anything?

Any help is appreciated. I am newbie to Symfony.

Thanks.

**Comment by Cholin2000** [comment]
The current solution is deprecated as it was created for Vue Storefront v1. For Vue Storefront 2 integration check out our GraphQL-based integration - https://github.com/BitBagCommerce/SyliusVueStorefront2Plugin
