### ISSUE TITLE
Values change in cart summary after refresh (for applied coupon)

### ISSUE THREAD

**Issue by Codeweld** [BitBagCommerce/SyliusVueStorefrontPlugin#68]
## Current behavior
Values change after refresh when promotion is applied to the cart for logged in customer - tax is increasing and grand total/subtotal is changing.
It's not working properly due to `adjustmentsTotal` being invalid for `OrderItemUnit` - it is growing after each refresh.

It’s working well for a guest user.

## Expected behavior
Refreshing should not affect values in cart summary.

## Steps to reproduce the issue
- login to your account
- add product to the cart
- add valid coupon to the cart
- refresh the page

## Suggested steps to fix the issue
- debug promotion logic to find why `adjustmentsTotal` for `OrderItemUnit` is growing

**Comment by Cholin2000** [comment]
The current solution is deprecated as it was created for Vue Storefront v1. For Vue Storefront 2 integration check out our GraphQL-based integration - https://github.com/BitBagCommerce/SyliusVueStorefront2Plugin
