### ISSUE TITLE
Deadlock occuring randomly

### ISSUE THREAD

**Issue by Codeweld** [BitBagCommerce/SyliusVueStorefrontPlugin#69]
## Current behavior
It happens that deadlock occurs during standard operations in VSF. It is related to `Timestampable` which is trying to modify `updated_at` of currently processed object.

![update](https://user-images.githubusercontent.com/50198366/74089036-24721a80-4a9d-11ea-8db1-190d418be115.png)

## Expected behavior
Deadlocks should not happen.

## Steps to reproduce the issue
It occurs during standard operations in VSF, just:
- login to your account
- modify content of your cart
- ...deadlock should be found eventually

## Suggested steps to fix the issue
- give up on `doctrine_transaction` middleware in messenger
- custom middleware for doctrine transactions implementing retries in case of a deadlock

**Comment by dperkosan** [comment]
I tried to test it with `doctrine_close_connection` instead of `doctrine_transaction`, but deadlock still appears.

**Comment by dperkosan** [comment]
btw, I removed `- doctrine_transaction` from middleware and problem still exists.

**Comment by Offcurve** [comment]
Thank you for sharing what you've discovered.
We will look into that soon, it's a critical issue and has to be resolved.

**Comment by diimpp** [comment]
That's a typical issue with sylius in asyc environments. Each api request, that triggers `order_processing` can be executed in parallel for the same order, which will result in deadlocks, weird price adjustments, inconsistent totals. (This probably related as well https://github.com/BitBagCommerce/SyliusVueStorefrontPlugin/issues/68)

Reason is that order consist of several tables and doctrine transaction is not longer enough to ensure data consistency. 

Solution is to wrap whole `order_processing` in business transaction, for example with pessimistic lock via `symfony/lock`
Something like `LockingOrderProcessor`, which will decorate `CompositeOrderProcessor` with appropriate priority should do the trick.

More on the topic
https://github.com/Sylius/ShopApiPlugin/issues/667

**Comment by Cholin2000** [comment]
The current solution is deprecated as it was created for Vue Storefront v1. For Vue Storefront 2 integration check out our GraphQL-based integration - https://github.com/BitBagCommerce/SyliusVueStorefront2Plugin
