### ISSUE TITLE
Cart desynchronization

### ISSUE THREAD

**Issue by Codeweld** [BitBagCommerce/SyliusVueStorefrontPlugin#70]
## Current behavior
Sometimes cart for logged in user is lost and guest’s one is assigned. Order can be made but it is not present in user’s order history.

## Expected behavior
Cart should stay the same.

## Steps to reproduce the issue
It occurs randomly during standard operations in VSF. 
Should be debbuged further to find a pattern.

## Suggested steps to fix the issue
- find an edge case in VSF logic when cart is lost
- decide whether can it be fixed from backend and implement solution if so

**Comment by Cholin2000** [comment]
The current solution is deprecated as it was created for Vue Storefront v1. For Vue Storefront 2 integration check out our GraphQL-based integration - https://github.com/BitBagCommerce/SyliusVueStorefront2Plugin
