### ISSUE TITLE
Product category can be accessed only through UI

### ISSUE THREAD

**Issue by Codeweld** [BitBagCommerce/SyliusVueStorefrontPlugin#71]
## Current behavior
After refresh (or just by typing an url into the browser bar) product category page cannot be found.

![nopage](https://user-images.githubusercontent.com/50198366/74093107-c9a4e700-4acd-11ea-8a0f-287b029ae229.png)

## Expected behavior
It should work for the same url - regardless it’s accessed through UI or typed into the browser bar.

## Steps to reproduce the issue
- open product category page using UI
- refresh the page or copy an url and open it independently

## Suggested steps to fix the issue
- according to VSF developers it can be a SSR-related problem

**Comment by Cholin2000** [comment]
The current solution is deprecated as it was created for Vue Storefront v1. For Vue Storefront 2 integration check out our GraphQL-based integration - https://github.com/BitBagCommerce/SyliusVueStorefront2Plugin
