### ISSUE TITLE
No thumbnails for configurable products in 'My order'

### ISSUE THREAD

**Issue by Codeweld** [BitBagCommerce/SyliusVueStorefrontPlugin#72]
## Current behavior
Only simple products in `My orders` profile section have thumbnails properly rendered. Configurable products have only placeholder image.

![thumbnail](https://user-images.githubusercontent.com/50198366/74093147-361fe600-4ace-11ea-8cb8-329a98c4c4cc.png)

## Expected behavior
Both types of products should have thumbnails properly rendered.

## Steps to reproduce the issue
- login to your account
- add two products to your cart - simple and configurable one
- go through checkout
- check `My orders` section

## Suggested steps to fix the issue
- check the VSF view rendering logic regarding `My orders` section

**Comment by Cholin2000** [comment]
The current solution is deprecated as it was created for Vue Storefront v1. For Vue Storefront 2 integration check out our GraphQL-based integration - https://github.com/BitBagCommerce/SyliusVueStorefront2Plugin
