### ISSUE TITLE
Remake order option does not work

### ISSUE THREAD

**Issue by Codeweld** [BitBagCommerce/SyliusVueStorefrontPlugin#73]
## Current behavior
`Remake order` option for specific order in `My orders` account section does not work. Trying it results with loading screen. 

It will be probably possible to fix with VSF v.1.12 – with use of custom ES queries.

![loading](https://user-images.githubusercontent.com/50198366/74093177-d1b15680-4ace-11ea-8db0-18c83c30a882.png)

## Expected behavior
`Remake order` option should work properly.

## Steps to reproduce the issue
- login to your account
- add product to your cart
- go through checkout
- try to remake order in `My orders` section

## Suggested steps to fix the issue
- wait for v.1.12 and custom ES queries

**Comment by Cholin2000** [comment]
The current solution is deprecated as it was created for Vue Storefront v1. For Vue Storefront 2 integration check out our GraphQL-based integration - https://github.com/BitBagCommerce/SyliusVueStorefront2Plugin
