### ISSUE TITLE
'My newsletter' does not work

### ISSUE THREAD

**Issue by Codeweld** [BitBagCommerce/SyliusVueStorefrontPlugin#74]
## Current behavior
`Update my preferences` button in `My newsletter` section does not work. It’s due to lack of `mailchimp` configuration.

## Expected behavior
`Update my preferences` button should allow to subscribe an user to the newsletter.

## Steps to reproduce the issue
- login to your account
- go to the `My newsletter` section in account overview
- try to use `Update my preferences` button

## Suggested steps to fix the issue
- configure `mailchimp` with VSF

**Comment by Cholin2000** [comment]
The current solution is deprecated as it was created for Vue Storefront v1. For Vue Storefront 2 integration check out our GraphQL-based integration - https://github.com/BitBagCommerce/SyliusVueStorefront2Plugin
