### ISSUE TITLE
Add to cart

### ISSUE THREAD

**Issue by dperkosan** [BitBagCommerce/SyliusVueStorefrontPlugin#84]
For add to cart, you should change file:
src/Entity/Order/OrderItem.php
line 8, into:
use BitBag\SyliusVueStorefrontPlugin\Sylius\Entity\Order\OrderItem as BaseOrderItem;

**Comment by Codeweld** [comment]
This one is mentioned in updated README. Thank you for this.
I'm closing this one as it's resolved now.
