### ISSUE TITLE
Problem with creating variant product

### ISSUE THREAD

**Issue by dperkosan** [BitBagCommerce/SyliusVueStorefrontPlugin#85]
On creating variant product and clicking "save", there is an error on saving that product in ES. That's because in the moment of saving product to ES, variant products are not yet created.

**Comment by Offcurve** [comment]
Could you provide more information about this error?

**Comment by dperkosan** [comment]
Sure,

1. Go to demo admin panel to create new project: https://syliusvsf.bitbag.shop/admin/products/new
2. Create configurable product:
![New product   Sylius](https://user-images.githubusercontent.com/12428970/77148259-7ab87d00-6a8f-11ea-8ef5-5521dfa579e9.png)
3. Click on save, and you will get:
 
// 20200320094149
// https://syliusvsf.bitbag.shop/admin/products/new

{
    "result": "Call to a member function getPath() on bool",
    "code": 500
}

**Comment by Offcurve** [comment]
Thank you, there is a problem indeed. 
We will fix it whenever it will be possible from our end.

Remember though that we always welcome PRs which will help us to develop this integration faster.

**Comment by silcki** [comment]
@Codeweld hello
I created the pull request where I fixed this bug
Could you please review it, please?
Because it's a very big issue when a client can't create a new product :)

**Comment by Cholin2000** [comment]
The current solution is deprecated as it was created for Vue Storefront v1. For Vue Storefront 2 integration check out our GraphQL-based integration - https://github.com/BitBagCommerce/SyliusVueStorefront2Plugin
