### ISSUE TITLE
"Automatic" creating cart for loggedin user

### ISSUE THREAD

**Issue by dperkosan** [BitBagCommerce/SyliusVueStorefrontPlugin#86]
There is a problem with "automatic" creating cart (new row in sylius.sylius_order) when logged in user hit API end point. It's working on single channel site, but not on multi-channel. 

I would try to fix it myself, but I'm having problem with finding piece of code in plugin that is responsible for cart creating. It seems to me there is some kind of listener that is creating cart when ever logged in user hit API end point.

**Comment by ognjenTomic** [comment]
Hello all, same problem here :/
Any updates on this topic? 

Tnx

**Comment by Offcurve** [comment]
Hello,

unfortunately we don't support multichanneling yet, but it's something that we will implement in the future for sure.

If you provide this functionality for you own, it would be great if you could make a PR with this.

**Comment by Cholin2000** [comment]
The current solution is deprecated as it was created for Vue Storefront v1. For Vue Storefront 2 integration check out our GraphQL-based integration - https://github.com/BitBagCommerce/SyliusVueStorefront2Plugin
