### ISSUE TITLE
Updating quantity

### ISSUE THREAD

**Issue by dperkosan** [BitBagCommerce/SyliusVueStorefrontPlugin#87]
Hello,
On changing quantity in cart, when "/api/cart/update?token=&cartId=xxxxxx" API end point is called immediately on every key-down (without delay), there is coming to inconsistency in the DB and calculation for cart is not correct.
On your demo page (https://vsf.bitbag.shop/) it seems that you have delay of about 1,5 sec before calling /api/cart/update?token=&cartId=xxxxxx  and there is no problem. 
How to handle it when calls are made one after another on VSF?

**Comment by dperkosan** [comment]
It seems this is Sylius problem. Basically, here is described same problem, but with different approach:
https://github.com/Sylius/ShopApiPlugin/issues/640

**Comment by ognjenTomic** [comment]
HI, same issue here, is there an override on this problem?

**Comment by Cholin2000** [comment]
The current solution is deprecated as it was created for Vue Storefront v1. For Vue Storefront 2 integration check out our GraphQL-based integration - https://github.com/BitBagCommerce/SyliusVueStorefront2Plugin
