### ISSUE TITLE
Deadlock

### ISSUE THREAD

**Issue by dperkosan** [BitBagCommerce/SyliusVueStorefrontPlugin#88]
Hi, guys. Please can you check this one:

1) Login
2) Add to cart
3) Logout
4) Login again
5) Refresh page couple of times and sylius_order table goes in deadlock

It happens in this file: vendor/bitbag/vuestorefront-plugin/src/Sylius/Provider/ShopUserAwareCustomerProvider.php 

but I'm not sure what and why is sylius_order table updated from there?

![deadlock](https://user-images.githubusercontent.com/12428970/79151881-8ddb1600-7dcb-11ea-9faa-dcc61b08f05b.png)

**Comment by Offcurve** [comment]
There is already an open issue #69  for that, so I'm closing this one. 
It's known issue probably related to `Timestampable`.
