### ISSUE TITLE
Not found etc/vsf-config/local.json

### ISSUE THREAD

**Issue by EvgKonkin** [BitBagCommerce/SyliusVueStorefrontPlugin#89]
Hello, I can not find the configuration file _etc/vsf-config/local.json_ in your repository that you specified in your readme.

`Copy etc/vsf-config/local.json file from this repository to config/local.json of Vue Storefront project directory.`

Where do you need to get the configuration for Vue Storefront? Thanks for the answer.

**Comment by maxmishyn** [comment]
Indeed local.json file with VueStoreFront connectivity configs is missing

**Comment by Offcurve** [comment]
Thank you very much!
`local.json` file is now in the repo.

Cheers and I'm closing this one
