### ISSUE TITLE
dependency on a non-existent service "bitbag_vue_storefront_plugin.command_bus"

### ISSUE THREAD

**Issue by crashbtz** [BitBagCommerce/SyliusVueStorefrontPlugin#94]
Hi,

When I install the plugin on Sylius 1.7.6, I have an error message saying:

`
The service "bitbag_sylius_vue_storefront_plugin.api.cart.create_cart" has a dependency on a non-existent service "bitbag_vue_storefront_plugin.command_bus".
`

Am I doing something wrong?

Thanks

**Comment by Codeweld** [comment]
Hi,
do you have this service specified in `src/Resources/config/config.yaml`?
We haven't tested this plugin on Sylius 1.7 though and there might be some issues.

**Comment by crashbtz** [comment]
No the service is defined anywhere.
But I don't get it, the "bitbag_vue_storefront_plugin.command_bus" service should not be defined in the plugin if you reference it?

**Comment by Codeweld** [comment]
Please run `bin/console debug:config framework` and send me block related to messenger

**Comment by crashbtz** [comment]
here what it says

![sylius](https://user-images.githubusercontent.com/4550542/87661311-b1ae4f00-c760-11ea-89dc-3d8f17ca161f.png)

**Comment by Codeweld** [comment]
Have you checked how the plugin behaves on Sylius 1.6? If not, please try.
As I mentioned before we had no time to update it to Sylius 1.7 yet, maybe this problem is somehow related.

**Comment by mraivaras** [comment]
I also facing the same issue on Sylius 1.6.0

**Comment by Codeweld** [comment]
Ok, I'll have a look into this as fast as possible. Thank you!

**Comment by EvgKonkin** [comment]
Hey. The problem will be solved if you create a file: **/config/packages/command_bus.yaml**

```yaml
framework:
  messenger:
    buses:
      bitbag_vue_storefront_plugin.command_bus:
        middleware:
          - doctrine_transaction
```

**Comment by crashbtz** [comment]
Yes indeed or if we import 

    - { resource: "@SyliusVueStorefrontPlugin/Resources/config/config.yml" }

**Comment by Codeweld** [comment]
You have to add the following line to the end of the `imports` section in your `config/packages/_sylius.yaml`:

```
- { resource: "@SyliusVueStorefrontPlugin/Resources/config/config.yaml" }
```

It's also mentioned in the new updated README. I'm closing this one as it's resolved.
