### ISSUE TITLE
Product view - add to cart

### ISSUE THREAD

**Issue by riadeveloper** [BitBagCommerce/SyliusVueStorefrontPlugin#97]
Sylius 1.7.4
PHP 7.4.6

The type of the "option_value" attribute for class "BitBag\SyliusVueStorefrontPlugin\Model\Request\Cart\CartItem\ConfigurableItemOption" must be one of "int" ("string" given).

File: BitBag\SyliusVueStorefrontPlugin\Model\Request\Cart\CartItem\ConfigurableItemOption
Line: 21

is
    /** @var int */
    public $option_value;

could be

    /** @var int|string */
    public $option_value;

**Comment by medteck** [comment]
I'm having the exact same issue.

**Comment by Codeweld** [comment]
Yes, it's a problem with deserialization as this value can be also an integer and a string sometimes.
Have you tested does your solution resolve the problem?

If so it would be great if you could open a PR and we'll test it whenever there will be some resources available.

Thank you for this!

**Comment by medteck** [comment]
Thanks! I've just submitted the PR to fix it #100
